name: Neocities CD

on:
  push:
    branches: [main]
  workflow_run:
    workflows: ["bookshelf"]
    types:
      - completed

concurrency: # prevent concurrent deploys doing strange things
  group: deploy-to-neocities
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install deps
        run:
          npm ci
      - name: Install sequoia
        run:
          npm i -g sequoia-cli
      - name: Publish to ATProto
        env:
          ATP_IDENTIFIER: ${{ secrets.ATP_IDENTIFIER }}
          ATP_APP_PASSWORD: ${{ secrets.ATP_APP_PASSWORD }}
        run:
          sequoia publish
      - name: build site
        run:
          npm run build
      - name: inject atUri link tags
        run:
          sequoia inject
      - name: Deploy to Neocities
        uses: bcomnes/deploy-to-neocities@v3
        with:
          api_key: ${{ secrets.NEOCITIES_API_TOKEN }}
          cleanup: true
          neocities_supporter: true
          dist_dir: _site
          protected_files: "*.png"
