name: Neocities CD

on:
  push:
    branches: [main]
  workflow_run:
    workflows: ["bookshelf"]
    types:
      - completed

concurrency: # prevent concurrent deploys doing strange things
  group: deploy-to-neocities
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.20.4
      - name: Install deps & build site
        run: |
          npm i
          npm run build

      - name: Deploy to Neocities
        uses: bcomnes/deploy-to-neocities@v1
        with:
          api_token: ${{ secrets.NEOCITIES_API_TOKEN }}
          cleanup: true
          dist_dir: _site
          protected_files: "*.png"
