name: pre-flight
on:
  push:
    branches-ignore:
      - main

jobs:
  copyedit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 26
      - name: Install deps
        run: npm ci
      - name: Check spelling
        run: npm run spellcheck
