name: Check teh spelling

on:
  pull_request:
    branches: 
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12
          cache: 'npm'
          
      - name: Install deps & run spellchecker
        run: |
          npm i
          npm run spellcheck
