name: Check teh spelling

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.14.0

      - name: Install deps
        run: npm i

      - name: Check spelling
        run: npm run spellcheck
